### ISSUE TITLE
subtitles视频滤镜不能使用自定义字体

### ISSUE THREAD

**Issue by cDQK** [magiclen/FFmpeg-CLI-For-Android#11]
安卓手机的，我看到别人说subtitles='subtitle.srt':fontsdir='fontsdir':force_style='fontname=fontname'可以编字幕。试了下会出现什么fonts.conf配置错误，然后提示默认使用DroidSansFallback字体，自定义的字体怎么设置才能用？谁知道吗？

**Comment by magiclen** [comment]
參數看起來沒問題，請確認fontsdir中確實有對應的字型檔。

**Comment by cDQK** [comment]
fontsdir目录确实有ttf字体的，使用的字体名称没加后缀，路径也是使用绝对路径的。真不知道问题出在哪 @magiclen

**Comment by magiclen** [comment]
能提供ffmpeg輸出到螢幕的訊息嗎？

**Comment by cDQK** [comment]
![IMG_20200403_165104x](https://user-images.githubusercontent.com/55192366/78343488-7df25380-75cd-11ea-94f0-a51a132d4826.jpg)
@magiclen

**Comment by magiclen** [comment]
移除掉fontsdir中的fonts.conf，你應該不需要這個。

另外底下還有訊息你的截圖沒有截到，如果字型套用正常，應該還會有下面這樣的訊息(以Noto Sans CJK TC Regular為例)：

```
[Parsed_subtitles_0 @ 0x562fbb123100] fontselect: (Noto Sans CJK TC Regular, 400, -1) -> NotoSansCJKtc-Regular, 0, NotoSansCJKtc-Regular
```

然後並不是所有字型都可以被正常設定，其實很多字型檔是會有問題的(除了不能當作內嵌字幕的字型外，內掛、外掛也會有問題，或者拿來當作Web Font來使用也是會有問題而無法正常套用)，遇到這類的字型檔在使用之前要先用別的工具修復一下。

**Comment by cDQK** [comment]
你的意思是字体库字体数量不全所以可能编制字体失败吗？我用的字体目录的确只有几个几百K的英文字体。
我试过了删除那个fonts.conf文件，但不知什么原因编译字幕总是失败，看不到任何字幕，把它放回去字幕就能编制成功！那个fonts.conf文件内容：

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>
	<its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
		<its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
	</its:rules>

	<description>Default configuration file</description>

<!--
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.

	The intent of this standard configuration file is to be adequate for
	most environments.  If you have a reasonably normal environment and
	have found problems with this configuration, they are probably
	things that others will also want fixed.  Please submit any
	problems to the fontconfig bugzilla system located at fontconfig.org

	Note that the normal 'make install' procedure for fontconfig is to
	replace any existing fonts.conf file with the new version.  Place
	any local customizations in local.conf which this file references.

	Keith Packard
-->

<!-- Font directory list -->
        <dir>/sdcard/Download/font</dir>
	<dir>/system/fonts</dir>
	<dir>/data/data/com.termux/files/usr/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>

<!--
  Accept deprecated 'mono' alias, replacing it with 'monospace'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>

<!--
  Accept alternate 'sans serif' spelling, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Accept deprecated 'sans' alias, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Load local system customization file
-->
	<include ignore_missing="yes">conf.d</include>

<!-- Font cache directory list -->

	<cachedir>/data/data/com.termux/files/usr/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<!-- the following element will be removed in the future -->
	<cachedir>~/.fontconfig</cachedir>

	<config>
<!--
  Rescan configuration every 30 seconds when FcFontSetList is called
 -->
		<rescan>
			<int>30</int>
		</rescan>
	</config>

</fontconfig>
```

还有shell变量：
FC_CONGIG_DIR=/sdcard/Download/font
FONTCONFIG_PATH=/sdcard/Download/font
FONTCONFIG_FILE=/sdcard/Download/font/fonts.conf

我再加几个系统大文件字体编译字幕确实成功了，不过还是有些小问题。总之谢谢你了😁
![Record_2020-04-04-08-32-42 00 00 11x](https://user-images.githubusercontent.com/55192366/78415405-1d5a2980-7654-11ea-934f-3e7fb6443ece.jpg)
![Record_2020-04-04-08-32-42 00 00 15x](https://user-images.githubusercontent.com/55192366/78415422-31059000-7654-11ea-907c-58ad307112c2.jpg)
@magiclen

**Comment by magiclen** [comment]
我說的不是字型檔缺字的問題，而是字型檔本身就有問題，舉例：Font Forge可以驗證字型是否有Missing Points at Extrema或是Self Intersecting的問題。

你如果要用fonts.conf，就不要把它放在fontsdir下，這樣FFmpeg會以為它是字型檔而嘗試讀取它(當然會讀取失敗，而出現「Error opening memory font」的訊息)。

既然都用環境變數指定fonts.conf了，其實也不需要在`-vf`設定fontsdir。

然後，根據你的截圖，你應該沒有成功套用Noto Sans CJK系列的字型。你的`NotoSansCJK-Regular.ttc`應該包含很多TTF，下fontname的時候要精準一點，才可以正確對應到字型，例如寫成：`Noto Sans CJK SC Regular`。

**Comment by cDQK** [comment]
好的 @magiclen

**Comment by cDQK** [comment]
作者，我还要麻烦一下😁
你说的能修复字体的“极点值缺失”和“自相交”问题是不是FontForge能修复的？我没电脑，手机安装不了这软件。你知不道有什么现成的可用字体啊？我下了好多中文字体都没用

**Comment by magiclen** [comment]
是如何沒用？能提供FFmpeg的輸出訊息嗎？

**Comment by cDQK** [comment]
屏幕信息太长了，截不了，我想这个问题解决了！
大概情况是我的fontsdir目录只有几个中文字体，分别是Adobe FangSong Std R仿宋STD R字体、RS_Song利方宋体、simsun宋体，我设置Fontname为利方宋体或者宋体的时候它都选择为Adobe的仿宋字体，仿宋字体编进字幕成功！一把Adobe的仿宋体删除就会默认使用Fallback字体，后来我注意到那个ass字幕文件里Style开头那行有Serif字样，之前编制视频时提示的fontselect说的都是它，我它改成“宋体”或者“利方宋体”没想到居然有用，成功编进去了。还有之前提示fontselect那行我不知道为什么我选用的字体会失败，那个0x200B和字体后面的400是什么意思，我猜它可能是字体高宽度的意思不知道对不对？我在网上找不到答案，不过也不纠结这什么意思了，字体都可以用了。麻烦你了

**Comment by magiclen** [comment]
0x200B是U+200B (zero-width space character)，出現那個訊息表示你字型檔缺這個字。400是一般字重regular。

恭喜成功燒製字幕啦！其實這非常簡單，但是一堆人都在問。絕大部分的人都是問一問就跑掉了，很少人會弄到最後。而且事實上這問題也跟我的這個應用程式沒什麼直接關聯，這根本只是FFmpeg的用法而已...

**Comment by cDQK** [comment]
哦，谢谢！我没问题了
