### ISSUE TITLE
是否支援rtmp output？

### ISSUE THREAD

**Issue by moondigi** [magiclen/FFmpeg-CLI-For-Android#2]
![screenshot_2016-05-13-11-02-27](https://cloud.githubusercontent.com/assets/8404678/15236775/92651d4a-18fa-11e6-93e5-fd1ba05fc548.png)

**Comment by magiclen** [comment]
Why you have a 'ffmpeg' argument?

**Comment by moondigi** [comment]
ok ic...thx for your reply
