### ISSUE TITLE
怎样执行“d”或“Ctrl＋C”

### ISSUE THREAD

**Issue by liuxue0905** [magiclen/FFmpeg-CLI-For-Android#5]
我使用您的客户端执行以下ffmpeg命令：

```
ffmpeg -i rtsp://XXX -acodec copy -vcodec copy /XXX/XXX.mp4
```

在macOS和Linux上，录制结束可以在终端中输入命令“d”／“Ctrl＋C”，这样视频文件会被正确收尾，可以正常播放。直接关闭终端当然文件没有收尾，无法播放。

使用您的客户端，可以看到正在录制的mp4文件，但是接下来如何执行结束的命令“d”／“Ctrl＋C”进行收尾呢？

**Comment by magiclen** [comment]
目前尚無法做到這個動作，這個問題將會在未來的版本解決，感謝您提出的問題。

**Comment by liuxue0905** [comment]
你好，该答案感觉不够完美，请仅供参考：
https://github.com/WritingMinds/ffmpeg-android-java/issues/128

**Comment by magiclen** [comment]
感謝提供

**Comment by magiclen** [comment]
1.6.0之後已加入這項功能
